export const emptyDoctorForm = () => ({
  full_name: "",
  area_id: null,
  address_line1: "",
  address_line2: "",
  city: "",
  state: "",
  postal_code: "",
  degree: "",
  department: "",
  type_of_activity: "",
  number_of_visits: 0,
  mobile: "",
  hospital_number: "",
  gender: "",
  date_of_birth: "",
  wedding_anniversary: "",
  status: "active",
});
